# Generated by Django 4.2.5 on 2023-09-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_students_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('speed_kmph', models.IntegerField(default=60)),
                ('mileage', models.IntegerField(default=10)),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
